### ISSUE TITLE
Storage permission is already granted but still asks for it

### ISSUE THREAD

**Issue by CH4CK1** [Shumi-Project/SaaF-Android#1]
I have downloaded the installation package, installed it and opened SaaF. It asked for storage permission. I granted it but still asks me to grant again. And now it's stuck.

Device: Huawei Mate 10 Pro
Android Version: Android 10
![Screenshot_20211118_073714](https://user-images.githubusercontent.com/85882291/142352647-ea8acfa5-6bb7-43bc-baf4-fb15a19fdf10.jpg)

**Comment by CH4CK1** [comment]
> I have downloaded the installation package, installed it and opened SaaF. It asked for storage permission. I granted it but still asks me to grant again. And now it's stuck.
> 
> Device: Huawei Mate 10 Pro Android Version: Android 10 ![Screenshot_20211118_073714](https://user-images.githubusercontent.com/85882291/142352647-ea8acfa5-6bb7-43bc-baf4-fb15a19fdf10.jpg)

PS: Also tried to clear data but it didn't work. Also I tried using the latest debug version.

**Comment by AozoraDev** [comment]
Heyya!
Hmm... this seems to be happening because the new permission request on SaaF is only targeted at Android 11 and above.

I'll fix it right away.
Thanks

**Comment by AozoraDev** [comment]
Heyya!
Try [this one](https://github.com/Shumi-Project/SaaF-Android/actions/runs/1484245259)

If you still have problems with the storage permission, feel free to reopen this issue.
