### ISSUE TITLE
IMG Tool

### ISSUE THREAD

**Issue by 1934291047o** [Shumi-Project/SaaF-Android#4]
Hello, how did you get help from lsdsl? I want to study the img editing function, because the img tool cannot be downloaded directly in Chinese Mainland. Do you know how to edit img files? thank you

**Comment by AozoraDev** [comment]
Hello, there!
I'm not really helped by LSDsl.

The idx generator is the result of reverse engineering from the IMG Tool app.
I added their name in the repo to give credits
